### ISSUE TITLE
Wrong product-name in german Translation

### ISSUE THREAD

**Issue by Lemmork** [die-wegmeister/Wegmeister.Recaptcha#10]
Hi guys,

thanks for this recaptcha extension.
There is a typo in the german translation file ValitationErrors.xlf.
The product-name says: product-name="Wegweiser.Recaptcha", which should be product-name="Wegmeister.Recaptcha".
This causes german translations not to be shown.

Regards
Heiko

**Comment by Benjamin-K** [comment]
This is already fixed in Version 2.2+. So if you update your version you should get the correct translations. By the way: The product-name was wrong in all languages ;)
