### ISSUE TITLE
V2, V3 do not work with fusion based form builder.

### ISSUE THREAD

**Issue by ujamiiboerner** [die-wegmeister/Wegmeister.Recaptcha#18]
### Description

Neos: 5.3.1
neos/form-builder: 2.2.0
neos/form-fusionrenderer: 2.1.1
wegmeister/recaptcha: 2.3.0

I used the fusion based form builder, added a captcha and then an error occurred.

### Steps to Reproduce

1. Create Form in Backend
2. Select Fusion Preset
3. Add Captcha field.
4. Add Website Key and Secret.

#### Expected behavior

See the captcha.

#### Actual behavior
An error occurred:

> The Fusion object `Wegmeister.Recaptcha:CaptchaV2` cannot be rendered: Most likely you mistyped the prototype name or did not define the Fusion prototype with `prototype(Wegmeister.Recaptcha:CaptchaV2) < prototype ...` . Other possible reasons are a missing parent-prototype or a missing `@class` annotation for prototypes without parent. It is also possible your Fusion file is not read because of a missing `include:` statement.
> 
> neos_form<Neos.Fusion:Renderer>/ element<Neos.Form:Form>/ content<Neos.Fusion:Array>/ pages<Neos.Fusion:Collection>/ itemRenderer<Neos.Fusion:Renderer>/ element<Neos.Form:Page>/ content<Neos.Fusion:Array>/ elements<Neos.Fusion:Collection>/ itemRenderer<Neos.Fusion:Renderer>/

**Comment by Benjamin-K** [comment]
Can you show me your fusion file so i can confirm this? Didn't actually use this with fusion yet.

**Comment by Benjamin-K** [comment]
Ok, i made a quick check for this. If you want to use this package with the fusion based form renderer, the required fusion prototypes need to be created. Currrently, there are only Fluid based templates for the capture. Fell free to create a PR for this, as i will need some time to have enough free space for this. 
For a start, have a look at the [Neos.Form.FusionRenderer prototypes](https://github.com/neos/form-fusionrenderer/tree/master/Resources/Private/Fusion/Elements) to get started with. 
Feel free to ask for help.

**Comment by Benjamin-K** [comment]
#23 only fixes this for recaptcha V3, so I reopened this issue.

**Comment by Benjamin-K** [comment]
Works for V3 and currently no need for V2 to be added, so this will be closed.
