### ISSUE TITLE
V3 Template is broken with Neos 5.3

### ISSUE THREAD

**Issue by paavo** [die-wegmeister/Wegmeister.Recaptcha#19]
### Description
When using a V3 Captcha the Variables in the Fluid-Template do not get rendered. 

Example:
```
<script type="text/javascript">
--
  | window.grecaptchaElements = window.grecaptchaElements \|\| [];
  | var siteKey = '{element.properties.siteKey}';
  | var action = '{element.properties.action}';
  | var selector = '#{element.uniqueIdentifier}';
...
```

### Steps to Reproduce

1. Add a V3 Captcha

#### Expected behavior
Variable `{element.properties.siteKey}`should be replaced with the `siteKey`

#### Actual behavior
Variable `{element.properties.siteKey}` wont not rendered.

**Comment by Benjamin-K** [comment]
This issue was fixed with PR #20.
