### ISSUE TITLE
PHP 8 support

### ISSUE THREAD

**Issue by klfman** [die-wegmeister/Wegmeister.Recaptcha#21]
Would it be possible to add PHP 8 support to this package? I would love to upgrade my servers PHP version to 8.1

**Comment by paavo** [comment]
@Benjamin-K is there any Reason the package forces ` "php": "~7.0"`?

@klfman have you tested the package with PHP 8?

**Comment by klfman** [comment]
> @klfman have you tested the package with PHP 8?

No, I have not. Just tried a composer install with php8 active.

**Comment by Benjamin-K** [comment]
I think there should be no problem changing this to sth. like `"php": "~7.0 || ~8.0"`, but i didn't have the time to test this yet as we don't use this package very often. 

@klfman Could you try adding this folder to your `DistributionPackages` folder and change the php requirements to see if it works? If so, i will change it here, too

**Comment by paavo** [comment]
@Benjamin-K I just tried Wegmeister.Recaptcha with Neos 7.3 and PHP 8.0 and it works well 👍

**Comment by Benjamin-K** [comment]
I decided to remove the `php` requirements as [neos/form](https://github.com/neos/form/blob/master/composer.json) already has the required php version as a requirement. 
As of version 2.3.2 you should now be able to install this package with php 8, too
