### ISSUE TITLE
reCAPTCHA dependency

### ISSUE THREAD

**Issue by rowan-m** [die-wegmeister/Wegmeister.Recaptcha#7]
You have `google/recaptcha` as a dependency. I've recently updated this with a `1.2` release. It *should* be backwards compatible, but obviously you'd want to test that. Happy to respond to issues over at https://github.com/google/recaptcha

**Comment by rowan-m** [comment]
Yes, hopefully mostly backwards compatible but with more options to
override defaults, more verbose responses, and the extended validation.

**Comment by Benjamin-K** [comment]
I updated the dependency to the `1.2` release of `google/recaptcha`. I also updated the captcha and added a new version that does not need the extra validator but has the validator in the form element itself. I will add some more features if v3 if googles recaptcha is finally released.
